import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

const AboutP = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jack Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/JF.ico" />
        <noscript> You need to enable Javascript to run this website </noscript>
      </Head>

      <main className={styles.main}>
        <div className={styles.twoOneGrid}>
          <div className={styles.twoOneGridItem}>
            <div className={styles.gridChild}>
              <Image
                src={"/ContactMePage/MeV2.webp"}
                alt={"Jack Foot Logo"}
                className={styles.gridSquareImage}
                width={700}
                height={700}
              />
            </div>
          </div>
          <div className={styles.twoOneGridItem}>
            <h1 className={styles.smallTitle}>About</h1>
            <p className={styles.smallDescription}>
              I am a student and currently studying Product Design, Physics and
              Computer Science A-Levels. Product Design is my favourite subject
              and I love the work of designers such as Dieter Rams and Jony Ive.
              The creation of innovative and functional products that meet the
              needs and wants of customers and it really interests me and other
              peoples work inspires me to make my own. Good product design has
              the potential to increase sales and profitability, as well as
              improve customer satisfaction and loyalty. Customer experience is
              a thing that I really care about as when I use a product I know
              that I want it to be easy to use and be intuitive, as well as
              create a great experience when using it.
            </p>
            <p className={styles.smallDescription}>
              I have also taken a key part in the development of my school's
              Greenpower racing car, which is a fully electric car that competes
              in the Greenpower Challenge. I was part of both Mechancial and
              Electrical Engineering elements of the car. This has developed my
              skills in electrical circuits alongside my work in Physics, which
              has helped me to understand the fundamentals of electricity and
              how it works such as with potential divider circuits and
              Kirchoff's laws just as examples.
            </p>
            <p className={styles.smallDescription}>
              I am deeply interested in cars too, both in terms of the design
              and shape of cars, as well as the actual driving and how they feel
              behind the wheel. I find that cars and product design have lots in
              common as the shape and aesthetics of a car could make or break
              it, same as a product but the experience greatly impact how the
              end product works and how much the user ends up liking it.
            </p>
            <p className={styles.smallDescription}>
              In addition to this I am a passionate driver, who currently uses a
              racing simulator to drive virtually round some of the most famous
              circuits in the world, such as: Nurburgring, Nordschliefe, Brands
              Hatch, Spa Francorchamps, The Top Gear Test Track and many more. I
              hope to one day be able to drive my own track car to these
              circuits and experience them in real life. My all time favourite
              car is the classic 1987 Porsche 930 Turbo, with a 3.3L flat six
              air cooled engine, rear wheel drive, 4 seater, 2 door coupe. The
              lines of the car are perfect, and make the car look as though it
              is at speed, even at a stand still. Simply put, it is a work of
              art.
            </p>
            <p className={styles.smallDescription}>
              Whilst I say that the Porsche 930 Turbo is my favourite car, that
              doesn't mean to say there haven't been better iterations of the
              classic. The Singer 911 is a modern take on the 911, with a modern
              engine and drivetrain, but with the classic body and interior. The
              car is a masterpiece, and is a perfect example of how to modernise
              a classic car, whilst keeping the classic look and feel.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default AboutP;
