import Head from 'next/head'
import styles from '../styles/Home.module.css'

const GithubP = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jack Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/JF.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Github
        </h1>
        <p className={styles.code}>
          This page is still in development! Thanks for your patience.
        </p>
      </main>
    </div>
  )
}

export default GithubP;