import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Tilt from 'react-parallax-tilt'
import Link from '../components/NoScrollLink'


let CardTiltAngle:number = 20;
let CardPerspective:number = 2500;

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
          <title>Jack Website</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/JF.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Jack Foot
        </h1>

        <div className={styles.horizontalGrid}>
        <Tilt tiltMaxAngleX={CardTiltAngle} perspective={CardPerspective} gyroscope={true} tiltReverse={true}>
            <Link href='/productDesign'>
              <p className={styles.card}>
                <span className={styles.logoInvert}>
                  <Image src="/P-Logo.svg" alt="Jack Foot Logo" width={45} height={45}/>
                </span>
              </p>
            </Link>
          </Tilt>
          <Tilt tiltMaxAngleX={CardTiltAngle} perspective={CardPerspective} gyroscope={true} tiltReverse={true}>
            <Link href='/typescript'>
              <p className={styles.card}>
                <span className={styles.logoInvert}>
                  <Image src="/typescript.svg" alt="Typescript Logo" width={45} height={45}/>
                </span>
              </p>
            </Link>
          </Tilt>
          <Tilt tiltMaxAngleX={CardTiltAngle} perspective={CardPerspective} gyroscope={true} tiltReverse={true}>
            <Link href='/nodejs'>
              <p className={styles.card}>
                <span className={styles.logoInvert}>
                  <Image src={"/nodedotjs.svg"} alt="Node.js Logo" width={45} height={45} />
                </span>
              </p>
            </Link>
          </Tilt>
          <Tilt tiltMaxAngleX={CardTiltAngle} perspective={CardPerspective} gyroscope={true} tiltReverse={true}>
            <Link href='/github'>
              <p className={styles.card}>
                <span className={styles.logoInvert}>
                  <Image src={"/github.svg"} alt="Github Logo" width={45} height={45} />
                </span>
              </p>
            </Link>
          </Tilt>
          <Tilt tiltMaxAngleX={CardTiltAngle} perspective={CardPerspective} gyroscope={true} tiltReverse={true}>
            <Link href='/cSharp'>
              <p className={styles.card}>
                <span className={styles.logoInvert}>
                  <Image src="/csharp.svg" alt="C# Logo" width={45} height={45}/>
                </span>
              </p>
            </Link>
          </Tilt>
        </div>
        
        <p className={styles.description}>
          Hey I'm Jack.
          <br/> I'm a student and I love coding. I've been coding since 2021 and I'm currently learning Next.js and React.js, to make dynamic websites and high performance applications.
        </p>
        <p className={styles.description}>
          I'm currently studying Computer Science, Physics and Product Design A-Levels.
          <br/> I've also taken a key part in the development of my school's Greenpower racing car, which is a fully electric car that competes in the Greenpower Challenge. I was part of both Mechancial and Electrical Engineering elements of the car.
        </p>
      </main>
    </div>
  )
}

export default Home
