import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Tilt from 'react-parallax-tilt'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
          <title>Jack Website</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/JF.ico" />
      </Head>
      

      <main className={styles.main}>
        <div className={styles.backgroundGif}></div>
        <h1 className={styles.title}>
          Jack Foot
        </h1>

        <div className={styles.horizontalGrid}>
          <Tilt tiltMaxAngleX={10} perspective={2000} gyroscope={true}>
            <a href='/typescript'>
              <p className={styles.card}>
                <span className={styles.logoInvert}>
                  <Image src="/typescript.svg" alt="Typescript" width={45} height={45}/>
                </span>
              </p>
            </a>
          </Tilt>
          <Tilt tiltMaxAngleX={10} perspective={2000} gyroscope={true}>
            <a href='/nodejs'>
              <p className={styles.card}>
                <span className={styles.logoInvert}>
                  <Image src={"/nodedotjs.svg"} alt="Node.js Logo" width={45} height={45} />
                </span>
              </p>
            </a>
          </Tilt>
          <Tilt tiltMaxAngleX={10} perspective={2000} gyroscope={true}>
            <a href='/github'>
              <p className={styles.card}>
                <span className={styles.logoInvert}>
                  <Image src={"/github.svg"} alt="Github Logo" width={45} height={45} />
                </span>
              </p>
            </a>
          </Tilt>
          <Tilt tiltMaxAngleX={10} perspective={2000} gyroscope={true}>
            <a href='/cSharp'>
              <p className={styles.card}>
                <span className={styles.logoInvert}>
                  <Image src="/csharp.svg" alt="C#" width={45} height={45}/>
                </span>
              </p>
            </a>
          </Tilt>
          <Tilt tiltMaxAngleX={10} perspective={2000} gyroscope={true}>
            <a href='/autodeskConfusion360'>
              <p className={styles.card}>
                <span className={styles.logoInvert}>
                  <Image src="/autodesk.svg" alt="autodesk logo" width={45} height={45}/>
                </span>
              </p>
            </a>
          </Tilt>
        </div>
        
        <p className={styles.description}>
          Hey I'm Jack.
          <br/> I'm a student and I love coding. I've been coding since 2021 and I'm currently learning Next.js and React.js, to make dynamic websites and high performance applications.
        </p>
        <p className={styles.description}>
          I'm currently studying Computer Science, Physics and Product Design A-Level's and I'm hoping to go on to do a degree apprenticeship in software engineering.
          <br/> I've also taken a key part in the development of my school's Greenpower racing car, which is a fully electric car that competes in the Greenpower Challenge. I was part of both Mechancial and Electrical Engineering elements of the car.
        </p>        
      </main>

      <footer className={styles.footer}> {/*Links to socials*/}
        <a
          href="https://www.linkedin.com/in/jackfoot51889/"
          target="_blank"
          rel="noopener noreferrer"
        >
          {' '}
          <span className={styles.logoInvert}>
            <Image src="/linkedin.svg" alt="Linkedin Logo" width={22.5} height={22.5} />
          </span>
        </a>
        <a
        href="https://github.com/Magicoo51889"
        target="_blank"
        rel="noopener noreferrer"
        >
          {' '}
          <span className={styles.logoInvert}>
            <Image src="/github.svg" alt="Github Logo" width={22.5} height={22.5}/>
          </span>
        </a>
        <a
        href="https://twitter.com/jjaffff"
        target="_blank"
        rel="noopener noreferrer"
        >
          {' '}
          <span className={styles.logoInvert}>
            <Image src="/twitter.svg" alt="Twitter Logo" width={22.5} height={22.5}/>
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
