import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const TypescriptP = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Jack Website</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/JF.ico" />
            </Head>
            
            <header className='header'> 
                <ul>
                    <ul><a href='/'>Home</a></ul>
                    <ul><a href='/github'>Github</a></ul>
                    <ul><a href='/nodejs'>Node.js</a></ul>
                </ul>
            </header>
        </div>
    )
}

export default TypescriptP;