import Head from 'next/head'
import styles from '../styles/Home.module.css'

const TypescriptP = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jack Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/JF.ico" />
        <noscript> You need to enable Javascript to run this website </noscript>
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
            TypeScript
        </h1>
        <p className={styles.code}>
          This page is still in development! Thanks for your patience.
        </p>
      </main>
    </div>
  )
}

export default TypescriptP;